
interface _GlobalComponents {
      'NavOverlay': typeof import("../components/NavOverlay.vue")['default']
    'ProjectCarousel': typeof import("../components/ProjectCarousel.vue")['default']
    'ProjectCarouselCard': typeof import("../components/ProjectCarouselCard.vue")['default']
    'ProjectGrid': typeof import("../components/ProjectGrid.vue")['default']
    'ProjectGridCardOld': typeof import("..../components/ProjectGridCard-old.vue'default']
    'ProjectGridCard': typeof import("../components/ProjectGridCard.vue")['default']
    'ProjectHighlightCarousel': typeof import("../components/ProjectHighlightCarousel.vue")['default']
    'ProjectHighlightCarouselCard': typeof import("../components/ProjectHighlightCarouselCard.vue")['default']
    'ProjectPageHeader': typeof import("../components/ProjectPageHeader.vue")['default']
    'IconsIconCommunity': typeof import("../components/icons/IconCommunity.vue")['default']
    'IconsIconDocumentation': typeof import("../components/icons/IconDocumentation.vue")['default']
    'IconsIconEcosystem': typeof import("../components/icons/IconEcosystem.vue")['default']
    'IconsIconSupport': typeof import("../components/icons/IconSupport.vue")['default']
    'IconsIconTooling': typeof import("../components/icons/IconTooling.vue")['default']
    'OldProjectCarouselOld': typeof import("../components/old/ProjectCarousel_old.vue")['default']
    'OldProjectPageFourupOld': typeof import("../components/old/ProjectPageFourup_old.vue")['default']
    'OldProjectPageImageGalleryContainerOld': typeof import("../components/old/ProjectPageImageGalleryContainer_old.vue")['default']
    'OldProjectPageOneupOld': typeof import("../components/old/ProjectPageOneup_old.vue")['default']
    'OldProjectPageParagraphOld': typeof import("../components/old/ProjectPageParagraph_old.vue")['default']
    'OldProjectPageThreeupOld': typeof import("../components/old/ProjectPageThreeup_old.vue")['default']
    'OldProjectPageTwoupOld': typeof import("../components/old/ProjectPageTwoup_old.vue")['default']
    'OldProjectPageVideoOld': typeof import("../components/old/ProjectPageVideo_old.vue")['default']
    'ProjectPage': typeof import("../storyblok/ProjectPage.vue")['default']
    'ProjectPageFourup': typeof import("../storyblok/ProjectPageFourup.vue")['default']
    'ProjectPageHeaderBlock': typeof import("../storyblok/ProjectPageHeaderBlock.vue")['default']
    'ProjectPageImageGalleryContainer': typeof import("../storyblok/ProjectPageImageGalleryContainer.vue")['default']
    'ProjectPageOneup': typeof import("../storyblok/ProjectPageOneup.vue")['default']
    'ProjectPageParagraph': typeof import("../storyblok/ProjectPageParagraph.vue")['default']
    'ProjectPageThreeup': typeof import("../storyblok/ProjectPageThreeup.vue")['default']
    'ProjectPageTwoup': typeof import("../storyblok/ProjectPageTwoup.vue")['default']
    'ProjectPageVideo': typeof import("../storyblok/ProjectPageVideo.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtImg': typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']
    'NuxtPicture': typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
      'LazyNavOverlay': typeof import("../components/NavOverlay.vue")['default']
    'LazyProjectCarousel': typeof import("../components/ProjectCarousel.vue")['default']
    'LazyProjectCarouselCard': typeof import("../components/ProjectCarouselCard.vue")['default']
    'LazyProjectGrid': typeof import("../components/ProjectGrid.vue")['default']
    'LazyProjectGridCardOld': typeof import("..../components/ProjectGridCard-old.vue'default']
    'LazyProjectGridCard': typeof import("../components/ProjectGridCard.vue")['default']
    'LazyProjectHighlightCarousel': typeof import("../components/ProjectHighlightCarousel.vue")['default']
    'LazyProjectHighlightCarouselCard': typeof import("../components/ProjectHighlightCarouselCard.vue")['default']
    'LazyProjectPageHeader': typeof import("../components/ProjectPageHeader.vue")['default']
    'LazyIconsIconCommunity': typeof import("../components/icons/IconCommunity.vue")['default']
    'LazyIconsIconDocumentation': typeof import("../components/icons/IconDocumentation.vue")['default']
    'LazyIconsIconEcosystem': typeof import("../components/icons/IconEcosystem.vue")['default']
    'LazyIconsIconSupport': typeof import("../components/icons/IconSupport.vue")['default']
    'LazyIconsIconTooling': typeof import("../components/icons/IconTooling.vue")['default']
    'LazyOldProjectCarouselOld': typeof import("../components/old/ProjectCarousel_old.vue")['default']
    'LazyOldProjectPageFourupOld': typeof import("../components/old/ProjectPageFourup_old.vue")['default']
    'LazyOldProjectPageImageGalleryContainerOld': typeof import("../components/old/ProjectPageImageGalleryContainer_old.vue")['default']
    'LazyOldProjectPageOneupOld': typeof import("../components/old/ProjectPageOneup_old.vue")['default']
    'LazyOldProjectPageParagraphOld': typeof import("../components/old/ProjectPageParagraph_old.vue")['default']
    'LazyOldProjectPageThreeupOld': typeof import("../components/old/ProjectPageThreeup_old.vue")['default']
    'LazyOldProjectPageTwoupOld': typeof import("../components/old/ProjectPageTwoup_old.vue")['default']
    'LazyOldProjectPageVideoOld': typeof import("../components/old/ProjectPageVideo_old.vue")['default']
    'LazyProjectPage': typeof import("../storyblok/ProjectPage.vue")['default']
    'LazyProjectPageFourup': typeof import("../storyblok/ProjectPageFourup.vue")['default']
    'LazyProjectPageHeaderBlock': typeof import("../storyblok/ProjectPageHeaderBlock.vue")['default']
    'LazyProjectPageImageGalleryContainer': typeof import("../storyblok/ProjectPageImageGalleryContainer.vue")['default']
    'LazyProjectPageOneup': typeof import("../storyblok/ProjectPageOneup.vue")['default']
    'LazyProjectPageParagraph': typeof import("../storyblok/ProjectPageParagraph.vue")['default']
    'LazyProjectPageThreeup': typeof import("../storyblok/ProjectPageThreeup.vue")['default']
    'LazyProjectPageTwoup': typeof import("../storyblok/ProjectPageTwoup.vue")['default']
    'LazyProjectPageVideo': typeof import("../storyblok/ProjectPageVideo.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtImg': typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']
    'LazyNuxtPicture': typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
}

declare module '@vue/runtime-core' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module '@vue/runtime-dom' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const NavOverlay: typeof import("../components/NavOverlay.vue")['default']
export const ProjectCarousel: typeof import("../components/ProjectCarousel.vue")['default']
export const ProjectCarouselCard: typeof import("../components/ProjectCarouselCard.vue")['default']
export const ProjectGrid: typeof import("../components/ProjectGrid.vue")['default']
export const ProjectGridCardOld: typeof import("..../components/ProjectGridCard-old.vue'default']
export const ProjectGridCard: typeof import("../components/ProjectGridCard.vue")['default']
export const ProjectHighlightCarousel: typeof import("../components/ProjectHighlightCarousel.vue")['default']
export const ProjectHighlightCarouselCard: typeof import("../components/ProjectHighlightCarouselCard.vue")['default']
export const ProjectPageHeader: typeof import("../components/ProjectPageHeader.vue")['default']
export const IconsIconCommunity: typeof import("../components/icons/IconCommunity.vue")['default']
export const IconsIconDocumentation: typeof import("../components/icons/IconDocumentation.vue")['default']
export const IconsIconEcosystem: typeof import("../components/icons/IconEcosystem.vue")['default']
export const IconsIconSupport: typeof import("../components/icons/IconSupport.vue")['default']
export const IconsIconTooling: typeof import("../components/icons/IconTooling.vue")['default']
export const OldProjectCarouselOld: typeof import("../components/old/ProjectCarousel_old.vue")['default']
export const OldProjectPageFourupOld: typeof import("../components/old/ProjectPageFourup_old.vue")['default']
export const OldProjectPageImageGalleryContainerOld: typeof import("../components/old/ProjectPageImageGalleryContainer_old.vue")['default']
export const OldProjectPageOneupOld: typeof import("../components/old/ProjectPageOneup_old.vue")['default']
export const OldProjectPageParagraphOld: typeof import("../components/old/ProjectPageParagraph_old.vue")['default']
export const OldProjectPageThreeupOld: typeof import("../components/old/ProjectPageThreeup_old.vue")['default']
export const OldProjectPageTwoupOld: typeof import("../components/old/ProjectPageTwoup_old.vue")['default']
export const OldProjectPageVideoOld: typeof import("../components/old/ProjectPageVideo_old.vue")['default']
export const ProjectPage: typeof import("../storyblok/ProjectPage.vue")['default']
export const ProjectPageFourup: typeof import("../storyblok/ProjectPageFourup.vue")['default']
export const ProjectPageHeaderBlock: typeof import("../storyblok/ProjectPageHeaderBlock.vue")['default']
export const ProjectPageImageGalleryContainer: typeof import("../storyblok/ProjectPageImageGalleryContainer.vue")['default']
export const ProjectPageOneup: typeof import("../storyblok/ProjectPageOneup.vue")['default']
export const ProjectPageParagraph: typeof import("../storyblok/ProjectPageParagraph.vue")['default']
export const ProjectPageThreeup: typeof import("../storyblok/ProjectPageThreeup.vue")['default']
export const ProjectPageTwoup: typeof import("../storyblok/ProjectPageTwoup.vue")['default']
export const ProjectPageVideo: typeof import("../storyblok/ProjectPageVideo.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtImg: typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']
export const NuxtPicture: typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyNavOverlay: typeof import("../components/NavOverlay.vue")['default']
export const LazyProjectCarousel: typeof import("../components/ProjectCarousel.vue")['default']
export const LazyProjectCarouselCard: typeof import("../components/ProjectCarouselCard.vue")['default']
export const LazyProjectGrid: typeof import("../components/ProjectGrid.vue")['default']
export const LazyProjectGridCardOld: typeof import("..../components/ProjectGridCard-old.vue'default']
export const LazyProjectGridCard: typeof import("../components/ProjectGridCard.vue")['default']
export const LazyProjectHighlightCarousel: typeof import("../components/ProjectHighlightCarousel.vue")['default']
export const LazyProjectHighlightCarouselCard: typeof import("../components/ProjectHighlightCarouselCard.vue")['default']
export const LazyProjectPageHeader: typeof import("../components/ProjectPageHeader.vue")['default']
export const LazyIconsIconCommunity: typeof import("../components/icons/IconCommunity.vue")['default']
export const LazyIconsIconDocumentation: typeof import("../components/icons/IconDocumentation.vue")['default']
export const LazyIconsIconEcosystem: typeof import("../components/icons/IconEcosystem.vue")['default']
export const LazyIconsIconSupport: typeof import("../components/icons/IconSupport.vue")['default']
export const LazyIconsIconTooling: typeof import("../components/icons/IconTooling.vue")['default']
export const LazyOldProjectCarouselOld: typeof import("../components/old/ProjectCarousel_old.vue")['default']
export const LazyOldProjectPageFourupOld: typeof import("../components/old/ProjectPageFourup_old.vue")['default']
export const LazyOldProjectPageImageGalleryContainerOld: typeof import("../components/old/ProjectPageImageGalleryContainer_old.vue")['default']
export const LazyOldProjectPageOneupOld: typeof import("../components/old/ProjectPageOneup_old.vue")['default']
export const LazyOldProjectPageParagraphOld: typeof import("../components/old/ProjectPageParagraph_old.vue")['default']
export const LazyOldProjectPageThreeupOld: typeof import("../components/old/ProjectPageThreeup_old.vue")['default']
export const LazyOldProjectPageTwoupOld: typeof import("../components/old/ProjectPageTwoup_old.vue")['default']
export const LazyOldProjectPageVideoOld: typeof import("../components/old/ProjectPageVideo_old.vue")['default']
export const LazyProjectPage: typeof import("../storyblok/ProjectPage.vue")['default']
export const LazyProjectPageFourup: typeof import("../storyblok/ProjectPageFourup.vue")['default']
export const LazyProjectPageHeaderBlock: typeof import("../storyblok/ProjectPageHeaderBlock.vue")['default']
export const LazyProjectPageImageGalleryContainer: typeof import("../storyblok/ProjectPageImageGalleryContainer.vue")['default']
export const LazyProjectPageOneup: typeof import("../storyblok/ProjectPageOneup.vue")['default']
export const LazyProjectPageParagraph: typeof import("../storyblok/ProjectPageParagraph.vue")['default']
export const LazyProjectPageThreeup: typeof import("../storyblok/ProjectPageThreeup.vue")['default']
export const LazyProjectPageTwoup: typeof import("../storyblok/ProjectPageTwoup.vue")['default']
export const LazyProjectPageVideo: typeof import("../storyblok/ProjectPageVideo.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtImg: typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']
export const LazyNuxtPicture: typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']

export const componentNames: string[]
